In [4]:
# carregar biblioteca 
import pandas as pd
import seaborn as sns
import numpy as np

## Leitura do conjunto de dados

### pinguins

In [5]:
df_penguins = sns.load_dataset('penguins')
df_penguins

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,Male
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,Female
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,Female
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,Female
...,...,...,...,...,...,...,...
339,Gentoo,Biscoe,NaN,NaN,NaN,NaN,NaN
340,Gentoo,Biscoe,46.8,14.3,215.0,4850.0,Female
341,Gentoo,Biscoe,50.4,15.7,222.0,5750.0,Male
342,Gentoo,Biscoe,45.2,14.8,212.0,5200.0,Female
343,Gentoo,Biscoe,49.9,16.1,213.0,5400.0,Male

- Dicionário de Dados

In [50]:
dicionario_penguins = pd.DataFrame([
    {
        "Nome": "species",
        "Descricao": "Especie de pinguins",
        "Tipo": "Qualitativo",
        "Subtipo": "Nominal"
    },
    {
        "Nome": "island",
        "Descricao": "Ilha onde é localizado essa espécie de pinguim",
        "Tipo": "Qualitativo",
        "Subtipo": "Nominal"
    },
    {
        "Nome": "bill_length_mm",
        "Descricao":"Tamanho do bico do pinguim",
        "Tipo": "Quantitativo",
        "Subtipo": "Contínuo",
    },
     {
        "Nome": "bill_depth_mm",
        "Descricao":"Profundidade do bico do pinguim",
        "Tipo": "Quantitativo",
        "Subtipo": "Contínuo",
    },
     {
         "Nome": "flipper_length_mm",
        "Descricao":"Tamanho da nadadeira do pinguim",
        "Tipo": "Quantitativo",
        "Subtipo": "Contínuo",
    },
    {
        "Nome": "body_mass_g",
        "Descricao":"Massa corporal do pinguim",
        "Tipo": "Quantitativo",
        "Subtipo": "Contínuo",
    },
    {
        "Nome": "sex",
        "Descricao":"Sexo do pinguim",
        "Tipo": "Qualitativo",
        "Subtipo": "Nominal",
    },
])

#Imprimindo o DataFrame
dicionario_penguins

,Nome,Descricao,Tipo,Subtipo
0,species,Especie de pinguins,Qualitativo,Nominal
1,island,Ilha onde é localizado essa espécie de pinguim,Qualitativo,Nominal
2,bill_length_mm,Tamanho do bico do pinguim,Quantitativo,Contínuo
3,bill_depth_mm,Profundidade do bico do pinguim,Quantitativo,Contínuo
4,flipper_length_mm,Tamanho da nadadeira do pinguim,Quantitativo,Contínuo
5,body_mass_g,Massa corporal do pinguim,Quantitativo,Contínuo
6,sex,Sexo do pinguim,Qualitativo,Nominal

- Estatística de tendência central e dispersão

In [42]:
#Funções que calculam a moda, o intervalo e o intervalo interquartil

#Função para calcular a moda
def mode(column):
    mode = column.mode()
    if not mode.empty: 
        return mode.iloc[0]
    else:
        return None
    
#Função para calcular o intervalo
def intervalo(column):
    inter = column.max() - column.min()
    return inter

#Função para calcular o intervalo interquartil
def intervalo_interquartil(column):
    q1 = column.quantile(0.25)
    q3 = column.quantile(0.75)
    iqr = q3 - q1
    return iqr

In [45]:
# Lista para renomear o  titulo das colunas para melhor compreensão
novos_nomes = {
    'mean': 'Média',
    'median': 'Mediana',
    'std': 'Desvio Padrão',
    'var': 'Variância',
    'mode': 'Moda',
    'intervalo': 'Intervalo',
    'intervalo_interquartil': 'Intervalo Interquartil'
}

In [51]:
# Filtrar apenas as colunas numéricas
numeric_columns  = df_penguins.select_dtypes('float64')

# Adicionado o calculo das medidas de tendência central e dispersão
tendencia_central_e_dispersao_values =  numeric_columns .agg(['mean', 'median','std', 'var', mode, intervalo, intervalo_interquartil])

#Renomeando as colunas
tendencia_central_e_dispersao_values = tendencia_central_e_dispersao_values.rename(columns=novos_nomes)

#Imprimindo o DataFrame
tendencia_central_e_dispersao_values

,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g
mean,43.921930,17.151170,200.915205,4201.754386
median,44.450000,17.300000,197.000000,4050.000000
std,5.459584,1.974793,14.061714,801.954536
var,29.807054,3.899808,197.731792,643131.077327
mode,41.100000,17.000000,190.000000,3800.000000
intervalo,27.500000,8.400000,59.000000,3600.000000
intervalo_interquartil,9.275000,3.100000,23.000000,1200.000000

- Calculo estastítica de forma separada para cada variável categórica

In [52]:
# Criando uma lista com as colunas numericas
colunas_numericas = df_penguins.select_dtypes('float64').columns

      - Por Espécie

In [53]:
# Adicionado o calculo das medidas de tendência central e dispersão
values_by_species = (
    df_penguins
    .groupby('species')[colunas_numericas]
    .agg(['mean', 'median','std', 'var', mode, intervalo, intervalo_interquartil])
)

#Renomeando as colunas
values_by_species = values_by_species.rename(columns=novos_nomes)

#Imprimindo o DataFrame
values_by_species

          bill_length_mm                                                   \
                   Média Mediana Desvio Padrão  Variância  Moda Intervalo
species
Adelie         38.791391   38.80      2.663405   7.093725  41.1      13.9
Chinstrap      48.833824   49.55      3.339256  11.150630  51.3      17.1
Gentoo         47.504878   47.30      3.081857   9.497845  45.2      18.7

                                 bill_depth_mm                        ...  \
          Intervalo Interquartil         Média Mediana Desvio Padrão  ...
species                                                               ...
Adelie                     4.000     18.346358   18.40      1.216650  ...
Chinstrap                  4.725     18.420588   18.45      1.135395  ...
Gentoo                     4.250     14.982114   15.00      0.981220  ...

          flipper_length_mm                                   body_mass_g  \
                       Moda Intervalo Intervalo Interquartil        Média
species
Adelie                190.0      38.0                    9.0  3700.662252
Chinstrap             187.0      34.0                   10.0  3733.088235
Gentoo                215.0      28.0                    9.0  5076.016260

                                                                  \
          Mediana Desvio Padrão      Variância    Moda Intervalo
species
Adelie     3700.0    458.566126  210282.891832  3550.0    1925.0
Chinstrap  3700.0    384.335081  147713.454785  3400.0    2100.0
Gentoo     5000.0    504.116237  254133.180061  5000.0    2350.0


          Intervalo Interquartil
species
Adelie                     650.0
Chinstrap                  462.5
Gentoo                     800.0

[3 rows x 28 columns]

    - Por Ilha

In [55]:
# Adicionado o calculo das medidas de tendência central e dispersão
values_by_island = (
    df_penguins
    .groupby('island')[colunas_numericas]
    .agg(['mean', 'median','std', 'var', mode, intervalo, intervalo_interquartil])
)

#Renomeando as colunas
values_by_island = values_by_island.rename(columns=novos_nomes)

#Imprimindo o DataFrame
values_by_island

          bill_length_mm                                                   \
                   Média Mediana Desvio Padrão  Variância  Moda Intervalo
island
Biscoe         45.257485   45.80      4.772731  22.778965  45.2      25.1
Dream          44.167742   44.65      5.953527  35.444479  36.0      25.9
Torgersen      38.950980   38.90      3.025318   9.152549  34.6      12.5

                                 bill_depth_mm                        ...  \
          Intervalo Interquartil         Média Mediana Desvio Padrão  ...
island                                                                ...
Biscoe                      6.70     15.874850    15.5      1.820721  ...
Dream                      10.70     18.344355    18.4      1.133116  ...
Torgersen                   4.45     18.429412    18.4      1.339447  ...

          flipper_length_mm                                   body_mass_g  \
                       Moda Intervalo Intervalo Interquartil        Média
island
Biscoe                215.0      59.0                  20.50  4716.017964
Dream                 190.0      34.0                  10.25  3712.903226
Torgersen             190.0      34.0                   8.00  3706.372549

                                                                  \
          Mediana Desvio Padrão      Variância    Moda Intervalo
island
Biscoe     4775.0    782.855743  612863.114133  5000.0    3450.0
Dream      3687.5    416.644112  173592.315762  3400.0    2100.0
Torgersen  3700.0    445.107940  198121.078431  3700.0    1800.0


          Intervalo Interquartil
island
Biscoe                   1125.00
Dream                     556.25
Torgersen                 662.50

[3 rows x 28 columns]

    - Por Sexo

In [56]:
# Adicionado o calculo das medidas de tendência central e dispersão
values_by_sex = (
    df_penguins
    .groupby('sex')[colunas_numericas]
    .agg(['mean', 'median','std', 'var', mode, intervalo, intervalo_interquartil])
)

#Renomeando as colunas
values_by_sex = values_by_sex.rename(columns=novos_nomes)

#Imprimindo o DataFrame
values_by_sex

       bill_length_mm                                                   \
                Média Mediana Desvio Padrão  Variância  Moda Intervalo
sex
Female      42.096970    42.8      4.903476  24.044076  46.5      25.9
Male        45.854762    46.8      5.366896  28.803570  41.1      25.0

                              bill_depth_mm                        ...  \
       Intervalo Interquartil         Média Mediana Desvio Padrão  ...
sex                                                                ...
Female                   8.60     16.425455   17.00      1.795681  ...
Male                     9.35     17.891071   18.45      1.863351  ...

       flipper_length_mm                                   body_mass_g  \
                    Moda Intervalo Intervalo Interquartil        Média
sex
Female             187.0      50.0                   23.0  3862.272727
Male               190.0      53.0                   26.0  4545.684524

                                                               \
       Mediana Desvio Padrão      Variância    Moda Intervalo
sex
Female  3650.0    666.172050  443785.199557  3700.0    2500.0
Male    4300.0    787.628884  620359.259160  3900.0    3050.0


       Intervalo Interquartil
sex
Female                 1200.0
Male                   1412.5

[2 rows x 28 columns]